version: "3.6"
services:
  db_test:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    command: postgres -c max_connections=200 -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - 9432:5432
